# Use postgres/example user/password credentials
version: '3.7'

services:
  db:
    image: postgres
    container_name: recorderpod
    restart: always
    volumes:
      - ${MYDATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  mydata:
